name: Main Branch CI

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo message
        run: echo "Changes on ${{ github.ref }} branch detected, running CI to prepare for release"

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: node-app:latest