name: Release New Verion

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'Release version tag (e.g., v1.0.0)'
          required: true
          default: 'v1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Announce Release Start
        run: echo "Starting the release process for version ${{ inputs.version }}"
        
      - name: Release With Provided Tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/thuan-tong-codeleap/node-app-gitflow:latest
            ghcr.io/thuan-tong-codeleap/node-app-gitflow:${{ inputs.version }}
